---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# tag-push-verify-action
name: "🏷️ Verify Pushed Tag"
description: "Verifies action/workflow trigger was tag push of given type"

inputs:
  versioning:
    description: 'Tag/string versioning type to check/validate'
    required: false
    # Options: [semver|calver|none]
    default: 'semver'
  exit_on_fail:
    description: 'When set true will exit on failed validation'
    required: false
    default: 'true'

outputs:
  tag_push:
    description: 'Set true when action/workflow trigger was tag push'
    value: "${{ steps.event.outputs.tag_push }}"
  valid:
    description: 'Set true when pushed tag conforms to versioning type'
    value: "${{ steps.results.outputs.valid }}"
  tag:
    description: 'Set to the pushed tag value: github.ref_name'
    value: "${{ steps.refs.outputs.tag }}"
  dev_version:
    description: 'Set true if tag is a development version'
    value: "${{ steps.results.outputs.dev_version }}"

runs:
  using: 'composite'
  steps:
    - name: 'Report action/workflow environment/triggers'
      id: refs
      shell: bash
      run: |
        # Report action/workflow environment
        echo 'GitHub Action/Workflow Event/Triggers 💬'
        echo "GitHub ref: $GITHUB_REF"
        echo "GitHub ref type: $GITHUB_REF_TYPE"
        # For actions/workflows triggered by a tag push, this is the tag value
        echo "GitHub ref name: $GITHUB_REF_NAME 🏷️"
        echo "tag=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
        echo 'valid=false' >> "$GITHUB_OUTPUT"

    - name: 'Report GitHub event/trigger'
      id: 'event'
      shell: bash
      env:
        EXIT_ON_FAIL: ${{ inputs.exit_on_fail }}
      run: |
        # Report GitHub event/trigger
        if [ "$GITHUB_REF_TYPE" = 'tag' ]; then
          tag_push='true'
          echo 'Workflow/action trigger was tag push event ✅'
        else
          tag_push='false'
          if [ "f$EXIT_ON_FAIL" = "ftrue" ]; then
            echo 'Workflow/action trigger was NOT tag push event ❌'
            exit 1
          else
            echo 'Workflow/action trigger was NOT tag push event ⚠️'
          fi
        fi
        echo "tag_push=$tag_push" >> "$GITHUB_OUTPUT"

    - name: "Validate action inputs"
      # yamllint disable-line rule:line-length
      shell: bash
      env:
        VERSIONING: ${{ inputs.versioning }}
      run: |
        # Validate action inputs
        if [ "$VERSIONING" = 'semver' ] || \
          [ "$VERSIONING" = 'calver' ] || \
          [ "$VERSIONING" = 'none' ]; then
          echo 'Action inputs validated 💬'
        else
          echo "Error: invalid versioning input: $VERSIONING ❌"
          exit 1
        fi

    - name: 'Validate tag/string [semver]'
      if: inputs.versioning == 'semver'
      id: semver
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/tag-validate-semantic-action@96445f92479f91efd979dffb2e2610a32d7eccd0 # v0.2.1
      with:
        string: "${{ github.ref_name }}"
        exit_on_fail: "${{ inputs.exit_on_fail }}"

    - name: 'Validate tag/string [calver]'
      if: inputs.versioning == 'calver'
      id: calver
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/tag-validate-calver-action@67b782bb59d546ff92969b8401bc4ded3cbff890 # v0.1.2
      with:
        string: "${{ github.ref_name }}"
        exit_on_fail: "${{ inputs.exit_on_fail }}"

    - name: 'Set outputs and return results'
      id: results
      shell: bash
      env:
        VERSIONING: ${{ inputs.versioning }}
        EXIT_ON_FAIL: ${{ inputs.exit_on_fail }}
        SEMVER_OUTCOME: ${{ steps.semver.outcome }}
        CALVER_OUTCOME: ${{ steps.calver.outcome }}
        SEMVER_DEV: ${{ steps.semver.outputs.dev_version }}
        CALVER_DEV: ${{ steps.calver.outputs.dev_version }}
      run: |
        # Validation passed
        if [ "$SEMVER_OUTCOME" = 'success' ]; then
          echo 'Pushed tag conforms to Semantic Versioning ✅' \
            >> "$GITHUB_STEP_SUMMARY"
          echo 'valid=true' >> "$GITHUB_OUTPUT"
        elif [ "$CALVER_OUTCOME" = 'success' ]; then
          echo 'Pushed tag conforms to Calendar Versioning ✅' \
            >> "$GITHUB_STEP_SUMMARY"
          echo 'valid=true' >> "$GITHUB_OUTPUT"
        elif [ "$VERSIONING" = 'none' ]; then
          echo 'Tag validation not enabled for this action/workflow ⚠️' \
            >> "$GITHUB_STEP_SUMMARY"
          echo 'valid=untested' >> "$GITHUB_OUTPUT"
        else
          echo "Tag/string failed $VERSIONING validation ❌"
          echo 'valid=false' >> "$GITHUB_OUTPUT"
          if [ "f$EXIT_ON_FAIL" = "ftrue" ]; then
            exit 1
          fi
        fi

        # Flag when the tag/string indicates development version
        dev_version=false
        if [ "$SEMVER_DEV" = 'true' ] \
          || [ "$CALVER_DEV" = 'true' ]; then
          echo "Development/pre-release detected 🛠️" \
            >> "$GITHUB_STEP_SUMMARY"
          dev_version=true
        fi
        echo "dev_version=$dev_version" >> "$GITHUB_OUTPUT"
