---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running local action: ${{ github.repository }} [SemVer]"
        id: 'semver'
        uses: ./
        with:
          versioning: 'semver'
        # This action relies on a tag push and is non-trivial to test here
        # Local testing here expected to fail; will test downstream
        continue-on-error: true

      - name: "Running local action: ${{ github.repository }} [CalVer]"
        id: 'calver'
        uses: ./
        with:
          versioning: 'calver'
        # This action relies on a tag push and is non-trivial to test here
        # Local testing here expected to fail; will test downstream
        continue-on-error: true

      - name: "Validating local action: ${{ github.repository }}"
        # yamllint disable-line rule:line-length
        if: steps.semver.outcome == 'success' || steps.calver.outcome == 'success'
        shell: bash
        run: |
          # Validating local action
          echo "Error: testing without a pushed tag is expected to fail ❌" \
            >> "$GITHUB_STEP_SUMMARY"
          echo "Error: testing without a pushed tag is expected to fail ❌"
          exit 1
